name: Hexo site generator

on:
  issues:
  push:
    paths:
      - ".github/**"
      - "build/**"
      - "hexo/**"
  workflow_dispatch:

env:
  token: ${{ secrets.GITHUB_TOKEN }}
  repo: ${{ github.repository }}
  author: ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python3
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: |
          pip install requests || exit -1

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Hexo
        run: |
          npm install -g hexo-cli || exit -1

      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run scripts
        run: |
          chmod 755 scripts/* || exit -1
          ./scripts/1_query_issues.py -t ${token} -r ${repo} -a ${author} -f issues.json || exit -1
          ./scripts/2_issues_to_posts.py -r ${repo} -f issues.json -d hexo/source/_posts/ || exit -1
          ./scripts/3_gen_and_publish.sh || exit -1
